# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
    application:
        name: marketing
    profiles:
        active: #spring.profiles.active#
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
            mode: LEGACYHTML5

    data:
      mongodb:
        uri: mongodb://127.0.0.1:27017/test

#mongodb://sf-gyzb-db-18581865951.v2.tenxapp.com:27019/sf-gyzb
server:
  port: 80

marketing:
  wechat:
      appId: wx7adb909e7786311b
      appSecret: 62207563bdbacc8a026df875fa97b8eb
      authNotify: http://ab5c97c8.ngrok.io/wx/notifies/auth
  resourceBase: http://127.0.0.1/
  winTemplateId: jn4YganJxPM4ky7hEXTrBBB0tghfaVX2lO_BE-PFN6E

logging:
  config: classpath:logback.xml