# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
    data:
      mongodb:
        uri: mongodb://root:sfdb123@dds-bp1a6dbd87af41b41.mongodb.rds.aliyuncs.com:3717,dds-bp1a6dbd87af41b42.mongodb.rds.aliyuncs.com:3717/admin?replicaSet=mgset-3138253

server:
  port: 80

marketing:
  wechat:
      appId: wx7adb909e7786311b
      appSecret: 62207563bdbacc8a026df875fa97b8eb
      authNotify: http://gz.hibake.net/wx/notifies/auth
  resourceBase: http://gz.hibake.net/
  winTemplateId: jn4YganJxPM4ky7hEXTrBBB0tghfaVX2lO_BE-PFN6E

logging:
  config: classpath:logback.xml