# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
    data:
      mongodb:
        uri: mongodb://sf-gyzb-db:27017/sf-gyzb

server:
  port: 80

marketing:
  wechat:
      appId: wx7adb909e7786311b
      appSecret: 62207563bdbacc8a026df875fa97b8eb
      authNotify: http://gy.ihibake.com/wx/notifies/auth
  resourceBase: http://gy.ihibake.com
  winTemplateId: jn4YganJxPM4ky7hEXTrBBB0tghfaVX2lO_BE-PFN6E

logging:
  config: classpath:logback.xml